CREATE TABLESPACE SPRING_CLOUD_DATA DATAFILE 'E:\Oracle\springcloud2020\SPRING_CLOUD_DATA.dbf' SIZE 1G
AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL
AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;