CREATE USER springcloud2020 IDENTIFIED BY springcloud2020
DEFAULT TABLESPACE SPRING_CLOUD_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON SPRING_CLOUD_DATA;


GRANT CREATE PROCEDURE TO springcloud2020;
GRANT CREATE SEQUENCE TO springcloud2020;
GRANT CREATE SESSION TO springcloud2020;
GRANT CREATE SYNONYM TO springcloud2020;
GRANT CREATE TABLE TO springcloud2020;
GRANT CREATE TRIGGER TO springcloud2020;
GRANT CREATE TYPE TO springcloud2020;
GRANT CREATE VIEW TO springcloud2020;
GRANT SELECT ANY DICTIONARY TO springcloud2020;
COMMIT;
